# Site settings
title: "Julian Weiss"
description: "Hire a freelance, full-stack software developer!"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Julian Weiss"
resume_title:                   "Freelance Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "me@insanj.com"
resume_header_contact_info:     "<i class='em em-blowfish no-print'></i> Fishtown, Philadelphia, PA â€¢ <i class='em em-mailbox_with_mail no-print'></i> me@annaraykovska.com"

display_header_contact_info:    "true"

resume_header_intro: "<p>ğŸŸ 23-year old entrepreneur based in <b>Fishtown, Philadelphia, PA</b>.</p><p><b>ğŸ¨ Full-stack software developer</b>, design pragmatist, music enthusiast, college grad.</p><p>ğŸ’ª I have been freelancing and creating open source projects for <b>over seven years</b>.</p><p>ğŸŒ† Before publishing my own apps on the App Store and working as a <b>fulltime engineer in NYC and Philly</b>, I created hundreds of community-driven ideas from Minecraft mods to Jailbreak tweaks.</p><p>ğŸŒ Now I am a completely independent freelancer looking for creative opportunities that <b>make the world a better place.</b></p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/insanj/resume"
  resume_twitter_url:           "https://twitter.com/insanj"
  resume_linkedin_url:          "https://www.linkedin.com/in/insanj"
  resume_instagram_url:         "https://www.instagram.com/insanj"
  resume_website_url:           "https://insanj.com"
  resume_medium_url:            "https://medium.com/@insanj"
resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
